### ISSUE TITLE
it crash when I try to open

### ISSUE THREAD

**Issue by lorypelli** [face-hh/fextify#1]
I changed the path in the `main.rs` file but it crash when I try to open (also, it will be good if you improve it to automatically create a path in our system). In this way, you can give us executable file

**Comment by face-hh** [comment]
Hey there! I assume you recompiled the program, could you instead try running it under Dev (npm run tauri dev) and send me the error you're getting?

**Comment by lorypelli** [comment]
![image](https://github.com/face-hh/fextify/assets/87276663/c75eda60-afd8-4c99-b0ff-164ca9bb010b)

**Comment by face-hh** [comment]
Create a file in the folder you made called "config.json", fill it with:
```json
{
"opened": [],
"children": []
}```

**Comment by face-hh** [comment]
> > Create a file in the folder you made called "config.json", fill it with:
> > 
> > ```json
> > {
> > "opened": [],
> > "children": []
> > }
> > ```
> 
> Can you please make that it does it automatically?

I'll try :^)

**Comment by face-hh** [comment]
Fixed in f84cd4b
