### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Polygons1** [face-hh/fextify#28]
do you need this script?

<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/2.3.1/list.min.js"></script>

if yes, change the // to https:// because the protocol is tauri://

(I am asking because there is an error in the console)

**Comment by face-hh** [comment]
I'll check in the next release.

**Comment by face-hh** [comment]
Turns out it's not needed, it will be removed in the next version.
