### ISSUE TITLE
License

### ISSUE THREAD

**Issue by winnietthepooh** [face-hh/fextify#3]
In the United States (where I somewhat understand copyright law) the author has full control over the code. As it is explicitly stated in the README it is for people to run and build the code but not edit it. In this instance the author has given permission to use the exe file and build the project with npm and nothing else.

Also because there is no license if the code causes damage the author may be held responsible. 

I personally prefer licenses like MIY but any other FOSS license will do such as MPL, GPL, and BSD

**Comment by face-hh** [comment]
I've added a Apache License 2.0 license, thanks for reporting this!
