### ISSUE TITLE
Themes cannot close

### ISSUE THREAD

**Issue by xpeuvr327** [face-hh/fextify#30]
when pressig ctrl+alt+s, themes dialog box opens, but cannot be closed. why not closing it when clicking in the zone outside the box

**Comment by face-hh** [comment]
You can press the same combination of keys to close it, similar to the command pallet: `CTRL` + `ALT` + `S`.

I will add the `ESC` option to it in the next release, and perhaps take a look into making them close when you click anywhere else.

**Comment by xpeuvr327** [comment]
wait, esc already closes it
