### ISSUE TITLE
Linux Support 

### ISSUE THREAD

**Issue by Ala-Alsanea** [face-hh/fextify#32]
release a Linux version pls ...

**Comment by face-hh** [comment]
An .AppImage and .deb version will be included in the next release.

**Comment by face-hh** [comment]
Added [here](https://github.com/face-hh/fextify/releases/tag/1.1.5)

**Comment by Ala-Alsanea** [comment]
> Added [here](https://github.com/face-hh/fextify/releases/tag/1.1.5)

my man <3
