### ISSUE TITLE
Fextify v1.1.5 not launching

### ISSUE THREAD

**Issue by OkGameStudios** [face-hh/fextify#35]
whenever i launch the exe on windows it gives me this error: `the code execution cannot proceed because WebView2Loader.dll was not found`. previous version work for me

**Comment by OkGameStudios** [comment]
> whenever i launch the exe on windows it gives me this error: `the code execution cannot proceed because WebView2Loader.dll was not found`. previous version work for me

**Comment by face-hh** [comment]
I updated the releases with the correctly compile binaries
