### ISSUE TITLE
Feature request: basic HTML export from Markdown

### ISSUE THREAD

**Issue by Wilker-uwu** [face-hh/fextify#5]
so consider this:

[Neocities](https://neocities.org/) is a spiritual revival of Geocities. people post their websites in their own little subdomains. i love it, and i wanna keep my own public little space there.

"What's up with that related to this project?"

i hate writing html and css. i just wanna have it easier on me to just have a page with some plain basic simple to the point vapt vupt html tagging and some plain basic simple to the point vapt vupt css template for text to have some plain basic sim-  markdown formatting with my background image and text background (scrolling tiled image of course).

this project would be perfect for having some basic html exporting for as long as its minimal like this,

...optionally with a basic templating for css because why not

###### also if you could make it more straightforward to do `cargo install --git <this repo>` on Linux that would be great. thank you :heart:

**Comment by face-hh** [comment]
Added in 0b1d6d8 via `Ctrl` + `Shift` + `H` or Command Pallet
